<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120928151155 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE snippet (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, syntax VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE snippets_tags (snippet_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_1D7B31866E34B975 (snippet_id), INDEX IDX_1D7B3186BAD26311 (tag_id), PRIMARY KEY(snippet_id, tag_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE snippets_tags ADD CONSTRAINT FK_1D7B31866E34B975 FOREIGN KEY (snippet_id) REFERENCES snippet (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE snippets_tags ADD CONSTRAINT FK_1D7B3186BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE snippets_tags DROP FOREIGN KEY FK_1D7B31866E34B975");
        $this->addSql("ALTER TABLE snippets_tags DROP FOREIGN KEY FK_1D7B3186BAD26311");
        $this->addSql("DROP TABLE snippet");
        $this->addSql("DROP TABLE snippets_tags");
        $this->addSql("DROP TABLE tag");
    }
}
